set -g mouse on
set -g copy-command "xsel --clipboard --input"

# Vi-style copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xsel --clipboard --input"
